self_explanatory_med_names = [
                'adenosine',
                'lorazepam',
                'azithromycin',
                'dextran',
                'phenylephrine',
                'norepinephrine',
                'epinephrine',
                'vasopressin',
                'midazolam',
                'ondansetron',
                'fentanyl',
                'cefazolin',
                'lidocaine',
                'remifentanil',
                'rocuronium',
                'succinylcholine',
                'propofol',
                'acetaminophen',
                'heparin',
                'aminocaproic',
                'furosemide',
                'ephedrine',
                'amiodarone',
                'ciprofloxacin',
                'gentamicin',
                'sufentanil',
                'alfentanil',
                'vancomycin',
                'tranexamic',
                'esmolol',
                'metoclopramide',
                'dopamine',
                'morphine',
                'dexmedetomidine',
                'diphenhydramine',
                'dexamethasone',
                'hydromorphone',
                'clindamycin',
                'protamine',
                'flumazenil',
                'ropivacaine',
                'bupivacaine',
                'neostigmine',
                'ketamine',
                'sugammadex',
                'labetalol',
                'famotidine',
                'ketorolac',
                'ceftriaxone',
                'ertapenem',
                'methylprednisolone',
                'bicitra',
                'scopolamine',
                'promethazine',
                'cisatracurium',
                'cefoxitin',
                'oxytocin',
                'mepivacaine',
                'etomidate',
                'nitroglycerin',
                'nitroprusside',
                'glycopyrrolate',
                'meperidine',
                'albuterol',
                'normosol',
                'moxifloxacin',
                'rifampin',
                'terbutaline',
                'indocy',
                'calcium chloride',
                'methadone',
                'zosyn',
                'insulin',
                'ampicillin-sulbactam',
                'ampicillin',
                'vecuronium',
                'hydrocortisone',
                'prochlorperazine',
                'metronidazole',
                'glucagon',
                'antithymocyte',
                'milrinone',
                'hexastarch',
                'hetastarch',
                'dobutamine',
                'metoprolol',
                'levofloxacin',
                'haloperidol',
                'cocaine',
                'verapamil',
                'mannitol',
                'pantoprazole',
                'naloxone',
                'cefepime',
                'feiba',
                'sodium bicarbonate',
                'methylergonovine',
                'phenytoin',
                'carboprost',
                'd50',
                'oxymetazoline',
                'nitric oxide',
                'gabapentin',
                'atropine',
                'potassium chloride',
                'albumin 25%',
                'albumin 5%',
                'methylene blue',
                'octreotide',
                'nicardipine',
                'methohexital',
                'hydralazine',
                'novoseven',

        ]

io_concept_ids = {
10017: 'albumin 25%',
10018: 'albumin 5%',
10259: 'electrolyte-a solution',
10260: 'dextrose / sodium acetate 10% / 19.25meq',
10406: 'saline 3%',
10454: 'saline 0.9%',
10455: 'saline 0.45%',
10456: 'lactated ringers',
10457: 'normosol',
10458: 'hetastarch',
10459: 'pentastarch',
10460: 'dextrose / water 5%',
10461: 'dextrose / lactated ringers 5%',
10462: 'dextrose / water 10%',
10463: 'saline w/kcl 0.45% + 20 meq/l',
10464: 'saline w/kcl 0.9% + 20 meq/l',
10465: 'dextrose / saline 5% / 0.225%',
10466: 'dextrose / saline 5% / 0.45%',
10467: 'dextrose / saline 5% / 0.9%',
10468: 'dextrose / saline w/kcl 5% / 0.45% + 20 meq/l',
10469: 'dextrose / saline w/kcl 5% / 0.9% + 20 meq/l',
10470: 'dextrose / saline 10% / 0.45%',
10510: 'other fluid in, unspecified',
10539: 'dextrose 10% w/lr',
10548: 'plasmalyte 148 w/dextrose 5%',
10549: 'plasmalyte 56',
10550: 'other - fluid in (mixed in rapid infuser)',
10551: 'saline w/nahco3 0.45% + 150 meq/l',
10556: 'saline 23.4%',
10557: 'albumin 20%',
10558: 'dextrose / saline w/kcl 5% / 0.225% + 20 meq/l',
10559: 'dextrose / saline w/kcl 5% / 0.45% + 40 meq/l',
10588: 'dextrose / saline w/kcl 10% / 0.225% + 20 meq/l',
10594: 'dextrose / saline w/kcl 5% / 0.45% + 10 meq/l',
10601: 'hydroxyethyl starch 130/0.4 6% in 0.9% saline (voluven)',
10602: 'dextrose / saline 10% / 0.225%',
10605: 'hydroxyethyl starch 6% in lactated solution (hextend)',
10606: 'saline w/kcl 0.9% + 40 meq/l',
10607: 'saline 2%',
10608: 'enteral feeds',
10610: 'plasmalyte a (ph balanced)',
10613: 'dextrose / sodium chloride 5% / 0.3 %',
10614: 'dextrose / sodium chloride / potassium chloride 10% / 0.225 % / 1.5 meq',
10615: 'dextrose / sodium chloride / potassium chloride 5% / 0.45 % / 1.5 meq',
10622: 'dextrose / saline 10% / 0.9%',
10640: 'saline 5%',
10641: 'plasma protein fraction 5%',
10647: 'dextrose / saline w/kcl 5% / 0.9% + 40 meq/l',
10655: 'perfusion - cardioplegia volume (ml)',
10667: 'dextrose / saline 12.5% / 0.225%',
10668: 'perfusion - cardioplegia solution type: high k',
10670: 'perfusion - cardioplegia solution type: low k',
10671: 'perfusion - cardioplegia solution type: del nido',
10672: 'dextrose 10% / unspecified solution',
10674: 'dextrose / saline w/kcl 10% / 0.9% + 20 meq/l',
10676: 'dextrose 5% / unspecified solution',
10677: 'cardiopulmonary bypass pump prime',
10715: 'dextrose / saline 12.5% / 0.9%',
10723: 'dextrose / water w/kcl 5% / 10 meq/l',
10724: 'dextrose / saline w/kcl 5% / 30 meq/l',
10725: 'dextrose 20%',
10776: 'crrt solution',
10777: 'dextrose / saline w/kcl 10% / 0.225% + 10 meq/l',
10778: 'dextrose / saline w/kcl 10% / 0.45% + 10 meq/l',
10780: 'dextrose / saline w/kcl 5% / 0.225% + 10 meq/l',
10781: 'dextrose / saline w/kcl 10% / 0.9% + 10 meq/l',
10782: 'dextrose / saline w/kcl 5% / 0.9% + 10 meq/l',
10783: 'dextrose / saline 12.5% / 0.45%',
10784: 'dextrose / water 25%',
10785: 'dextrose / water 12.5%',
10786: 'dextrose / water 15%',
10787: 'dextrose / water 3%',
10812: 'isolyte s',
10832: 'saline 1.7%',
10833: 'dextrose / lactated ringers w/kcl 5% + 40meq/l',
11090: 'sterofundin',
11101: 'other fluid in, medication infusion volume',
10497: 'urine output',
10498: 'gastric tube oro, naso, or gastrostomy',
10499: 'estimated blood loss',
10500: 'ascites',
10501: 'cerebrospinal fluid lumbar drain',
10502: 'cerebrospinal fluid ventriculostomy',
10503: 'emesis',
10504: 'chest tube unspecified type',
10505: 'colostomy',
10506: 'small bowel ileostomy or jejunostomy',
10507: 'surgical drain hemovac, jackson-pratt, penrose, wound vac',
10508: 'ultrafiltration ultrafiltrate, cvvh',
10509: 'biliary ptc, t-tube',
10511: 'other output, unspecified',
10520: 'stool',
10544: 'chest tube pleural fluid',
10545: 'chest tube blood',
10546: 'cerebrospinal fluid unspecified site',
10604: 'cardiopulmonary bypass circuit pump',
10645: 'cellsaver output (not transfused)',
10656: 'perfusion - retrograde arterial prime, rap (ml)',
10657: 'perfusion - venous antegrade prime, vap (ml)',
10703: 'diaper output',
10775: 'crrt output',
50219: 'emesis ocurrence',
}

io_concepts_use = [ 10520, #'stool',
                    10499, #'estimated blood loss',
                    10497, #'urine output',
                    10503, #'emesis',
                    10775, #'crrt output',
                    10645, #'cellsaver output (not transfused)']
                ]


lab_concept_ids = {
3360: 'poc - activated clotting time (act)',
3361: 'poc - glucose (fingerstick)',
3362: 'poc - glucose (unspecified source)',
3363: 'formal lab - blood gas - methemoglobin',
3364: 'formal lab - blood gas - carboxyhemoglobin',
3365: 'poc - blood gas - sample type',
3366: 'formal lab - estimated glomerular filtration rate (african-american)',
3367: 'formal lab - estimated glomerular filtration rate (non african american)',
3368: 'poc - hcg, urine',
3369: 'formal lab - bilirubin total, body fluid (not serum/plasma)',
3370: 'poc - blood gas - ph (unknown sample type)',
3371: 'd-dimer',
3372: 'ph (venous cord blood)',
3373: 'ph (cord blood arterial)',
3374: 'hco3 (cord blood venous)',
3375: 'poc - blood gas - pco2 (unknown sample type)',
3376: 'hco3 (cord blood arterial)',
3377: 'base excess (cord blood venous)',
3378: 'base excess (cord blood arterial)',
3379: 'co2 (cord blood venous)',
3380: 'poc - blood gas - po2 (unknown sample type)',
3381: 'co2 (cord blood arterial)',
3382: 'po2 (cord blood arterial)',
3383: 'po2 (cord blood venous)',
3384: 'triidothyronine',
3385: 'poc - blood gas - sodium',
3386: 'thyroxine',
3387: 'formal lab - anion gap',
3388: 'formal lab - creatine kinase',
3389: 'formal lab - ck-mb',
3390: 'poc - blood gas - potassium',
3391: 'formal lab - creatine phosphokinase',
3392: 'formal lab - high-sensitivity cardiac troponin t (hs-ctnt) (ng/l)',
3393: 'rotem- uncategorized',
3394: 'thromboelastography (teg)- uncategorized',
3395: 'poc - blood gas - ionized calcium (mmol/l)',
3396: 'formal lab - cardiac troponin i (ctnl) ng/l',
3397: 'formal lab - high-sensitivity cardiac troponin t (hs-ctnt) (ng/ml)',
3398: 'formal lab - procalcitonin',
3399: 'formal lab - heparin level (low molecular weight heparin)',
3400: 'poc - blood gas - cl',
3401: 'formal lab - high-sensitivity cardiac troponin t (hs-ctnt) (pg/ml)',
3402: 'neutrophil gelatinase-associated lipocalin (ngal)',
3404: 'immunology - antibody - covid19 - igg',
3405: 'poc - blood gas - glucose',
3406: 'micro - culture - aerobic',
3407: 'specimen type',
3408: 'medication level - vancomycin (trough)',
3409: 'micro - gram stain',
3410: 'poc - blood gas - lactate (unknown sample type) (mmol/l)',
3411: 'medication level - vancomycin (peak)',
3412: 'medication level - vancomycin (random)',
3414: 'medication level - amikacin (trough)',
3415: 'poc - blood gas - hct measured',
3416: 'medication level - tobramycin (random)',
3417: 'medication level - tobramycin (trough)',
3418: 'micro - acid fast stain (afb)',
3419: 'formal lab - high-sensitivity cardiac troponin i (hs-ctni) (pg/ml)',
3420: 'poc - blood gas - o2 sat measured (unknown sample type)',
3421: 'virology - hiv',
3422: 'micro - methicillin resistant staphylococcus aureus (mrsa)',
3423: 'micro - clostridium difficile',
3424: 'micro - culture (unspecified)',
3425: 'poc - blood gas - base excess',
3427: 'formal lab - high-sensitivity cardiac troponin i (hs-ctni) (ng/l)',
3428: 'immunology - antibody - covid19 - igm',
3429: 'immunology - antibody - sars - cov-2 nucleocapsid protein',
3430: 'poc - blood gas - hco3',
3431: 'immunology - antibody - sars - cov-2 spike protein',
3432: 'micro – culture - group b streptococcus',
3433: 'poc – blood gas – hco3 (venous)',
3434: 'poc – blood gas – hco3 (mixed venous)',
3435: 'poc - hematocrit spun',
3436: 'poc – blood gas – pco2 (mixed venous)',
3437: 'poc – blood gas – po2 (mixed venous)',
3438: 'poc – blood gas – ph (mixed venous)',
3439: 'poc – blood gas – o2 sat measured (mixed venous)',
3440: 'poc - coulter counter - hemoglobin',
3441: 'formal lab - high-sensitivity c-reactive protein',
3442: 'formal lab - ammonia, serum/plasma',
3443: 'formal lab – cardiac troponin t (ctnt) ng/ml',
3444: 'poc - blood gas - ionized calcium (mg/dl)',
3445: 'poc - coulter counter - platelets',
3446: 'formal lab - ionized calcium, serum/plasma (mg/dl)',
3447: 'formal lab - blood gas - ionized calcium (mg/dl)',
3448: 'mcv - mean corpuscular volume',
3449: 'mch- mean corpuscular hemoglobin',
3450: 'poc - coulter counter - hematocrit',
3451: 'mchc - mean corpuscular hemoglobin concentration',
3452: 'rdw - red cell distribution of width',
3453: '% neutrophils',
3454: '% lymphocytes',
3455: 'poc - prothrombin time (pt)',
3456: '% monocytes',
3457: '% eosinophils',
3458: '% basophils',
3459: 'absolute neutrophils',
3460: 'poc - international normalized ratio (inr)',
3461: 'absolute lymphocytes',
3462: 'absolute monocytes',
3463: 'absolute eosinophils',
3464: 'absolute basophils',
3465: 'poc - partial thromboplastin time (ptt)',
3466: 'esr - erythrocyte sedimentation rate',
3467: 'thromboelastogram (teg) maximum amplitude (ma), millimeters',
3468: 'thromboelastogram (teg) kinetics (k), minutes',
3469: 'thromboelastogram (teg) lysis at 30 minutes (ly30), %',
3471: 'thromboelastogram (teg) alpha angle (a), degrees',
3472: 'thromboelastogram (teg) clotting reaction time (r), minutes',
3473: 'thromboelastogram (teg) maximum platelet activation by txa a2 (ma aa), millimeters',
3474: 'thromboelastogram (teg) maximum platelet activation by adp (ma adp), millimeters',
3478: 'thromboelastogram (teg) activated clotting time (t-act), seconds',
3479: 'poc - blood gas - lactate (unknown sample type) (mg/dl)',
3483: 'formal lab - lactate, serum/plasma (mg/dl)',
3484: 'formal lab - blood gas - lactate (unknown sample type) (mg/dl)',
3494: 'formal lab - blood gas - lactate (arterial) (mg/dl)',
3495: 'formal lab - activated partial thromboplastin time (aptt)',
3496: 'formal lab - creatinine, serum/plasma, mcmol/l',
3497: 'poc - glucose (fingerstick), mmol/l',
3498: 'poc - glucose (unspecified source), mmol/l',
3499: 'poc - blood gas - glucose, mmol/l',
3500: 'formal lab - glucose, serum/plasma, mmol/l',
3501: 'formal lab - blood gas - glucose, mmol/l',
3502: 'formal lab - hemoglobin, g/l',
3504: 'formal lab - blood gas - hemoglobin, g/l',
3505: 'poc - blood gas - hemoglobin, g/l',
3506: 'formal lab - cardiac troponin i (ctni) mcg/l',
3507: 'formal lab - high-sensitivity cardiac troponin i (hs-ctni) mcg/l',
3508: 'formal lab – cardiac troponin t (ctnt), mcg/l',
3509: 'formal lab - high-sensitivity cardiac troponin t (hs-ctnt), mcg/l',
3510: 'poc - coulter counter - hemoglobin, g/l',
5001: 'formal lab - potassium, serum/plasma',
5002: 'formal lab - creatinine, serum/plasma',
5003: 'formal lab - glucose, serum/plasma',
5004: 'formal lab - platelets',
5005: 'formal lab - hemoglobin',
5006: 'formal lab - hematocrit',
5007: 'formal lab - prothrombin time (pt)',
5008: 'formal lab - international normalized ratio (inr)',
5009: 'formal lab - partial thromboplastin time (ptt)',
5010: 'formal lab - magnesium, serum/plasma',
5011: 'formal lab - cardiac troponin i (ctnl) ng/ml',
5012: 'formal lab - blood urea nitrogen, serum/plasma',
5013: 'formal lab - fibrinogen',
5014: 'formal lab - bilirubin total, serum/plasma',
5015: 'formal lab - bilirubin unconjugated, serum/plasma',
5016: 'formal lab - bilirubin conjugated, serum/plasma',
5017: 'formal lab - thyroid stimulating hormone',
5018: 'formal lab - lactate, serum/plasma (mmol/l)',
5019: 'poc - parathyroid hormone',
5020: 'poc - blood gas - pco2 (arterial)',
5021: 'poc - blood gas - po2 (arterial)',
5022: 'poc - blood gas - ph (arterial)',
5023: 'poc - blood gas - pco2 (venous)',
5024: 'poc - blood gas - po2 (venous)',
5025: 'poc - blood gas - ph (venous)',
5026: 'formal lab - glycosylated hemoglobin, serum/plasma (hba1c)',
5027: 'formal lab - sodium, serum/plasma',
5028: 'formal lab - ionized calcium, serum/plasma (mmol/l)',
5029: 'formal lab - co2, serum/plasma',
5030: 'formal lab - chloride, serum/plasma',
5031: 'formal lab - ast (sgot), serum/plasma',
5032: 'formal lab - alt (sgpt), serum/plasma',
5033: 'formal lab - alkaline phosphatase, serum/plasma',
5034: 'formal lab - blood gas - base excess (unknown sample type)',
5035: 'formal lab - blood gas - chloride',
5036: 'formal lab - blood gas - glucose',
5037: 'formal lab - blood gas - hco3',
5038: 'formal lab - blood gas - hct measured',
5039: 'formal lab - blood gas - ionized calcium (mmol/l)',
5040: 'formal lab - blood gas - lactate (unknown sample type) (mmol/l)',
5041: 'formal lab - blood gas - o2 sat measured (unknown sample type)',
5042: 'formal lab - blood gas - pco2 (arterial)',
5043: 'formal lab - blood gas - pco2 (unknown sample type)',
5044: 'formal lab - blood gas - pco2 (venous)',
5045: 'formal lab - blood gas - ph (arterial)',
5046: 'formal lab - blood gas - ph (unknown sample type)',
5047: 'formal lab - blood gas - ph (venous)',
5048: 'formal lab - blood gas - po2 (arterial)',
5049: 'formal lab - blood gas - po2 (unknown sample type)',
5050: 'formal lab - blood gas - po2 (venous)',
5051: 'formal lab - blood gas - potassium',
5052: 'formal lab - blood gas - sample type',
5053: 'formal lab - blood gas - sodium',
5054: 'formal lab - amylase, serum/plasma',
5055: 'formal lab - lipase, serum/plasma',
5056: 'formal lab - white blood cell count',
5057: 'formal lab - albumin, serum/plasma',
5058: 'formal lab - calcium (total), serum/plasma',
5059: 'formal lab - total cholesterol',
5060: 'formal lab - hdl cholesterol',
5061: 'formal lab - ldl cholesterol',
5062: 'formal lab - protein (total), serum/plasma',
5063: 'formal lab - hcg, serum/plasma',
5064: 'formal lab - hcg, urine',
5065: 'formal lab - b-type natriuretic peptide, serum/plasma',
5066: 'formal lab - osmolality, serum/plasma',
5067: 'formal lab - triglycerides',
5068: 'formal lab - c-reactive protein',
5069: 'formal lab - phenytoin (total) level',
5070: 'medication level - digoxin',
5071: 'formal lab - phenytoin (free fraction) level',
5072: 'formal lab - ethanol level, serum/plasma',
5073: 'formal lab - phosphorus, serum/plasma',
5074: 'formal lab - lactate dehydrogenase',
5075: 'poc - blood gas - fio2',
5076: 'formal lab - blood gas - fio2',
5077: 'formal lab - blood bank antibody screen interpretation',
5078: 'formal lab - blood bank abo rh type interpretation',
5079: 'formal lab - activated clotting time (act)',
5080: 'formal lab - blood gas - hemoglobin',
5081: 'poc - blood gas - hemoglobin',
5082: 'formal lab - blood gas - o2 sat measured (arterial)',
5083: 'formal lab - blood gas - o2 sat measured (venous)',
5084: 'poc - blood gas - o2 sat measured (arterial)',
5085: 'poc - blood gas - o2 sat measured (venous)',
5086: 'formal lab - blood gas - lactate (arterial) (mmol/l)',
5087: 'formal lab - blood gas - base excess (arterial)',
5088: 'formal lab - blood gas - base excess (venous)',
5089: 'formal lab - free t4',
5090: 'formal lab - free t3',
5091: 'formal lab - parathyroid hormone',
5092: 'formal lab - miscellaneous sendout',
5093: 'formal lab - blood bank abo type interpretation (no rhesus factor)',
5094: 'formal lab - blood bank rhesus factor interpretation (no abo type)',
5095: 'formal lab - ionized magnesium, serum/plasma',
5104: 'formal lab - blood gas - base excess (mixed venous)',
5114: 'formal lab - blood gas - po2 (mixed venous)',
5124: 'formal lab - blood gas - pco2 (mixed venous)',
5134: 'formal lab - blood gas - hco3 (mixed venous)',
5144: 'formal lab - blood gas - ph (mixed venous)',
5154: 'formal lab - blood gas - o2 sat measured (mixed venous)',
5155: 'micro - culture - aerobic (blood)',
5156: 'micro - culture - afb (blood)',
5157: 'micro - culture - afb (non-blood)',
5158: 'micro - culture - anaerobic',
5159: 'micro - culture - anaerobic (blood)',
5160: 'micro - culture - fungus',
5161: 'micro - culture - fungus (blood)',
5162: 'micro - culture - yeast',
5163: 'micro - culture (blood)',
5164: 'micro - culture (csf)',
5165: 'micro - culture (deep tissue)',
5166: 'micro - culture (foreign body)',
5167: 'micro - culture (iv catheter tip)',
5168: 'micro - culture (non-sterile body fluid)',
5169: 'micro - culture (respiratory)',
5170: 'micro - culture (sterile body fluid)',
5171: 'micro - culture (stool)',
5172: 'micro - culture (urine)',
5173: 'micro - culture (urogenital)',
5174: 'micro - culture (wound)',
5175: 'micro - staphylococcus',
5176: 'micro - vancomycin resistant enterococcus (vre)',
5177: 'virology - adenovirus',
5178: 'virology - astrovirus',
5179: 'virology - coronavirus (sars-cov-2)',
5180: 'virology - human metapneumovirus',
5181: 'virology - human rhinovirus-enterovirus',
5182: 'virology - norovirus',
5183: 'virology - parainfluenze virus',
5184: 'virology - rotavirus',
5185: 'virology - respiratory synctial virus',
5186: 'virology - sapovirus',
5187: 'immunology - antibody - iga total',
5188: 'immunology - antibody - igg total',
5189: 'immunology - antibody - igm total',
5190: 'immunology - antibody - igg/igm',
5191: 'medication level - acetaminophen',
5192: 'medication level - acetone',
5193: 'medication level - amikacin (peak)',
5194: 'medication level - amikacin (random)',
5195: 'medication level - argatroban',
5196: 'medication level - carbamazepine',
5197: 'medication level - copper',
5198: 'medication level - cortisol',
5199: 'medication level - cyclosporine',
5200: 'medication level - dilantin',
5201: 'medication level - erythropoietin',
5202: 'medication level - estradiol',
5203: 'medication level - ethanol',
5204: 'medication level - ethylene glycol',
5205: 'medication level - folic acid',
5206: 'medication level - gentamicin (peak)',
5207: 'medication level - gentamicin (random)',
5208: 'medication level - gentamicin (trough)',
5209: 'medication level - hydroxycarbazepine',
5210: 'medication level - insulin',
5211: 'medication level - iron',
5212: 'medication level - tobramycin (peak)',
}


io_concept_ids = {
10017: 'albumin 25%',
10018: 'albumin 5%',
10259: 'electrolyte-a solution',
10260: 'dextrose / sodium acetate 10% / 19.25meq',
10406: 'saline 3%',
10454: 'saline 0.9%',
10455: 'saline 0.45%',
10456: 'lactated ringers',
10457: 'normosol',
10458: 'hetastarch',
10459: 'pentastarch',
10460: 'dextrose / water 5%',
10461: 'dextrose / lactated ringers 5%',
10462: 'dextrose / water 10%',
10463: 'saline w/kcl 0.45% + 20 meq/l',
10464: 'saline w/kcl 0.9% + 20 meq/l',
10465: 'dextrose / saline 5% / 0.225%',
10466: 'dextrose / saline 5% / 0.45%',
10467: 'dextrose / saline 5% / 0.9%',
10468: 'dextrose / saline w/kcl 5% / 0.45% + 20 meq/l',
10469: 'dextrose / saline w/kcl 5% / 0.9% + 20 meq/l',
10470: 'dextrose / saline 10% / 0.45%',
10510: 'other fluid in, unspecified',
10539: 'dextrose 10% w/lr',
10548: 'plasmalyte 148 w/dextrose 5%',
10549: 'plasmalyte 56',
10550: 'other - fluid in (mixed in rapid infuser)',
10551: 'saline w/nahco3 0.45% + 150 meq/l',
10556: 'saline 23.4%',
10557: 'albumin 20%',
10558: 'dextrose / saline w/kcl 5% / 0.225% + 20 meq/l',
10559: 'dextrose / saline w/kcl 5% / 0.45% + 40 meq/l',
10588: 'dextrose / saline w/kcl 10% / 0.225% + 20 meq/l',
10594: 'dextrose / saline w/kcl 5% / 0.45% + 10 meq/l',
10601: 'hydroxyethyl starch 130/0.4 6% in 0.9% saline (voluven)',
10602: 'dextrose / saline 10% / 0.225%',
10605: 'hydroxyethyl starch 6% in lactated solution (hextend)',
10606: 'saline w/kcl 0.9% + 40 meq/l',
10607: 'saline 2%',
10608: 'enteral feeds',
10610: 'plasmalyte a (ph balanced)',
10613: 'dextrose / sodium chloride 5% / 0.3 %',
10614: 'dextrose / sodium chloride / potassium chloride 10% / 0.225 % / 1.5 meq',
10615: 'dextrose / sodium chloride / potassium chloride 5% / 0.45 % / 1.5 meq',
10622: 'dextrose / saline 10% / 0.9%',
10640: 'saline 5%',
10641: 'plasma protein fraction 5%',
10647: 'dextrose / saline w/kcl 5% / 0.9% + 40 meq/l',
10655: 'perfusion - cardioplegia volume (ml)',
10667: 'dextrose / saline 12.5% / 0.225%',
10668: 'perfusion - cardioplegia solution type: high k',
10670: 'perfusion - cardioplegia solution type: low k',
10671: 'perfusion - cardioplegia solution type: del nido',
10672: 'dextrose 10% / unspecified solution',
10674: 'dextrose / saline w/kcl 10% / 0.9% + 20 meq/l',
10676: 'dextrose 5% / unspecified solution',
10677: 'cardiopulmonary bypass pump prime',
10715: 'dextrose / saline 12.5% / 0.9%',
10723: 'dextrose / water w/kcl 5% / 10 meq/l',
10724: 'dextrose / saline w/kcl 5% / 30 meq/l',
10725: 'dextrose 20%',
10776: 'crrt solution',
10777: 'dextrose / saline w/kcl 10% / 0.225% + 10 meq/l',
10778: 'dextrose / saline w/kcl 10% / 0.45% + 10 meq/l',
10780: 'dextrose / saline w/kcl 5% / 0.225% + 10 meq/l',
10781: 'dextrose / saline w/kcl 10% / 0.9% + 10 meq/l',
10782: 'dextrose / saline w/kcl 5% / 0.9% + 10 meq/l',
10783: 'dextrose / saline 12.5% / 0.45%',
10784: 'dextrose / water 25%',
10785: 'dextrose / water 12.5%',
10786: 'dextrose / water 15%',
10787: 'dextrose / water 3%',
10812: 'isolyte s',
10832: 'saline 1.7%',
10833: 'dextrose / lactated ringers w/kcl 5% + 40meq/l',
11090: 'sterofundin',
11101: 'other fluid in, medication infusion volume',
10497: 'urine output',
10498: 'gastric tube oro, naso, or gastrostomy',
10499: 'estimated blood loss',
10500: 'ascites',
10501: 'cerebrospinal fluid lumbar drain',
10502: 'cerebrospinal fluid ventriculostomy',
10503: 'emesis',
10504: 'chest tube unspecified type',
10505: 'colostomy',
10506: 'small bowel ileostomy or jejunostomy',
10507: 'surgical drain hemovac, jackson-pratt, penrose, wound vac',
10508: 'ultrafiltration ultrafiltrate, cvvh',
10509: 'biliary ptc, t-tube',
10511: 'other output, unspecified',
10520: 'stool',
10544: 'chest tube pleural fluid',
10545: 'chest tube blood',
10546: 'cerebrospinal fluid unspecified site',
10604: 'cardiopulmonary bypass circuit pump',
10645: 'cellsaver output (not transfused)',
10656: 'perfusion - retrograde arterial prime, rap (ml)',
10657: 'perfusion - venous antegrade prime, vap (ml)',
10703: 'diaper output',
10775: 'crrt output',
50219: 'emesis ocurrence',
}

physiologic_concept_ids = {
                            3000: 'Unmapped Physiologic Concept',
                            3001: 'Perfusion- Cardiopulmonary Flow (ml/min)',
                            3002: 'Perfusion- Cardiopulmonary Line Pressure (mmHg)',
                            3003: 'Perfusion- Cardiopulmonary volume (ml)',
                            3004: 'Inhaled Monitor Calculated MAC Equivalent',
                            3005: 'EKG Pulse Rate',
                            3006: 'Isoflurane actual consumption (ml)',
                            3007: 'Desflurane actual consumption (ml)',
                            3008: 'Sevoflurane actual consumption (ml)',
                            3009: 'BIS - Suppression Ratio',
                            3010: 'SpO2 Pulse Rate',
                            3011: 'BP Sys Invasive Unspecified Site 1',
                            3012: 'BP Dias Invasive Unspecified Site 1',
                            3013: 'BP Mean Invasive Unspecified Site 1',
                            3014: 'BIS - Total Power',
                            3015: 'BP Sys Non-invasive',
                            3016: 'Pulse Pressure Variation',
                            3017: 'Regional Oxygen Saturation',
                            3018: 'Regional Oxygen Saturation Baseline',
                            3019: 'Stroke Volume Variation',
                            3020: 'BP Dias Non-invasive',
                            3021: 'Non-invasive Total Hemoglobin Concentration',
                            3022: 'Stroke Volume',
                            3023: 'Stroke Volume Index',
                            3024: 'Stroke Volume Variance Index',
                            3025: 'BP Mean Non-invasive',
                            3026: 'BP Sys Invasive Unspecified Site 4',
                            3027: 'BP Dias Invasive Unspecified Site 4',
                            3028: 'BP Mean Invasive Unspecified Site 4',
                            3029: 'Cardiac output - Arterial line',
                            3030: 'BP Sys Arterial Line (Invasive, Peripheral)',
                            3031: 'Temperature - Temporal Artery',
                            3032: 'Exhaled Monitor Calculated MAC Equivalent',
                            3033: 'Train-of-four Quantitative (Objective, From Device) Count',
                            3034: 'Trigger Sensitivity Flow (L/min)',
                            3035: 'BP Dias Arterial Line (Invasive, Peripheral)',
                            3036: 'Perfusion - Cardiopulmonary bypass pump FiO2%',
                            3037: 'Perfusion - Cardiopulmonary bypass pump Co2 (L/min)',
                            3038: 'Perfusion - Cardiopulmonary bypass pump isoflurane %',
                            3039: 'Perfusion - Cardiopulmonary bypass sweep gas flow (mL/min)',
                            3040: 'BP Mean Arterial Line (Invasive, Peripheral)',
                            3041: 'BP Sys Invasive Unspecified Site 2',
                            3042: 'BP Dias Invasive Unspecified Site 2',
                            3043: 'BP Mean Invasive Unspecified Site 2',
                            3044: 'Perfusion - Cardiopulmonary bypass arterial fill volume (mL)',
                            3045: 'SpO2 %',
                            3046: 'BP Sys Invasive Unspecified Site 3',
                            3047: 'BP Dias Invasive Unspecified Site 3',
                            3048: 'BP Mean Invasive Unspecified Site 3',
                            3049: 'Perfusion - Cardiopulmonary bypass venous fill volume (mL)',
                            3050: 'Temp 1 - Unspecified Site',
                            3051: 'Temp 2 - Unspecified Site',
                            3052: 'Temp 1 - Monitoring Site',
                            3053: 'Temp 2 - Monitoring Site',
                            3054: 'Temperature - Skin',
                            3055: 'Temperature - Esophageal',
                            3056: 'Temperature - Blood',
                            3057: 'Temperature - Tympanic',
                            3058: 'Temperature - Bladder',
                            3059: 'Temperature - Nasopharyngeal',
                            3060: 'Temperature - Axillary',
                            3061: 'Temperature - Rectal',
                            3062: 'Temperature - Myocardial',
                            3065: 'BP Sys Aorta',
                            3067: 'Perfusion - Cardiopulmonary bypass index pump flow (mL/min/m2)',
                            3068: 'Vaporizer Setting (%)',
                            3070: 'BP Dias Aorta',
                            3072: 'Perfusion - Bypass Pump RPM',
                            3073: 'Pulmonary Vascular Resistance Index',
                            3074: 'Airway- Supplemental Oxygen',
                            3075: 'BP Mean Aorta',
                            3076: 'Aldrete Score',
                            3077: 'Arousal Level',
                            3078: 'Glasgow Coma Scale (GCS) Score',
                            3079: 'Glasgow - Best Motor Response',
                            3080: 'Central Venous Pressure',
                            3081: 'Glasgow - Best Verbal Response',
                            3082: 'Glasgow - Best Eye Response',
                            3083: 'Braden Score',
                            3084: 'Confusion Assessment Method (CAM) Score',
                            3085: 'Cardiac output - thermodilution',
                            3086: 'Pain Score (Generic)',
                            3087: 'Pain Score (FLACC)',
                            3088: 'Pain Score (Visual Analog Scale)',
                            3089: 'Pain Score (Faces)',
                            3090: 'Cardiac index - thermodilution',
                            3091: 'Pain Assessment Tool',
                            3092: 'Level of Consciousness',
                            3093: 'Sedation Assessment (Pasero Opioid Induced Sedation Scale)',
                            3094: 'Sedation Assessment (Richmond Agitation Sedation Scale-RASS)',
                            3095: 'Cardiac output - continuous',
                            3096: 'Positioning',
                            3097: 'FLACC Score: Face',
                            3098: 'FLACC Score: Legs',
                            3099: 'FLACC Score: Activity',
                            3100: 'Cardiac index - continuous',
                            3101: 'FLACC Score: Cry',
                            3102: 'Cardiac Ouput - Non-Invasive',
                            3103: 'Cardiac index - Non-Invasive',
                            3104: 'FLACC Score: Consolability',
                            3105: 'SvO2 %',
                            3106: 'Braden Score: Friction and Shear',
                            3107: 'Braden Score: Sensory Perception',
                            3108: 'Braden Score: Mobility',
                            3109: 'Braden Score: Moisture',
                            3110: 'Systemic Vascular Resistance',
                            3111: 'Braden Score: Activity',
                            3112: 'Braden Score: Nutrition',
                            3113: 'Fall Risk: History of Falling',
                            3114: 'Fall Risk- Secondary Diagnosis',
                            3115: 'Pulmonary artery occlusion pressure',
                            3116: 'Fall Risk- Ambulatory Aid',
                            3117: 'Fall Risk- IV/Hep Lock',
                            3118: 'Fall Risk- Gait/Transferring',
                            3119: 'Fall Risk- Mental Status',
                            3120: 'Pulmonary artery pressure Sys',
                            3121: 'Systemic Vascular Resistance Index (SVRI)',
                            3122: 'Patient warming method - generic',
                            3123: 'FLACC - Rest or Activity',
                            3124: 'Sedation Assessment (RAMSAY Scale)',
                            3125: 'Pulmonary artery pressure Dias',
                            3127: 'Modified Early Warning Sign Score (MEWS)',
                            3128: 'Perfusion Index',
                            3129: 'Pleth Variability Index',
                            3130: 'Pulmonary artery pressure Mean',
                            3131: 'Perfusion - Cardiopulmonary bypass sweep gas flow (L/min)',
                            3132: 'rSO2 Index Cerebral',
                            3133: 'rSO2 Index Unspecified Site',
                            3134: 'Delirium Assessment Score (AWOL)',
                            3135: 'Left Atrial Pressure (Mean)',
                            3136: 'Right atrial pressure',
                            3137: 'Right Ventricular Pressure - Sys',
                            3138: 'Right Ventricular Pressure - Dias',
                            3139: 'Right Ventricular Pressure - Mean',
                            3140: 'ICP pressure mean',
                            3141: 'Cerebral Perfusion Pressure',
                            3142: 'Patient State Index - Spectral Edge Frequency Left (SEFL)',
                            3143: 'Patient State Index - Spectral Edge Frequency Right (SEFR)',
                            3145: 'ST Lead I',
                            3147: 'Patient State Index - Artifact (ARTF)',
                            3148: 'Sedation Level',
                            3149: 'Supplemental O2 (FiO2% or L/min)',
                            3150: 'ST Lead II',
                            3151: 'Ventilator I:E Ratio I-Component',
                            3152: 'Ventilator I:E Ratio E-Component',
                            3153: 'Sequential Organ Failure Assessment (SOFA)',
                            3154: 'Aldrete Score: Activity',
                            3155: 'ST Lead III',
                            3156: 'ST Lead IV',
                            3157: 'Aldrete Score: Respiration',
                            3158: 'Aldrete Score: Circulation',
                            3159: 'Aldrete Score: Consciousness',
                            3160: 'ST aVF',
                            3161: 'Aldrete Score: SpO2/Oxygenation',
                            3162: 'Apnea Time (secs)',
                            3163: 'ST Lead V5',
                            3164: 'Pupil Assessment',
                            3165: 'ST aVL',
                            3166: 'Fetal Heart Rate Category',
                            3167: 'Pressure Support: Delta PPS (cmH20)',
                            3168: 'BiPAP/CPAP - Pressure Support',
                            3169: 'Pediatric Early Warning Score (PEWS)',
                            3170: 'ST aVR',
                            3173: 'Intra-Aortic Balloon Pump (IABP) - Augmented MAP',
                            3174: 'Intra-Aortic Balloon Pump (IABP) - Augmented Systolic BP',
                            3175: 'ST Lead V1',
                            3176: 'Intra-Aortic Balloon Pump (IABP) - Augmented Diastolic BP',
                            3177: 'Sedation Assessment Scale (Generic)',
                            3178: 'Procedure Table Position',
                            3179: 'Arm Position',
                            3180: 'Respiratory Rate by EKG Bioimpedence',
                            3181: 'Frequency of Contractions',
                            3182: 'Ventilator Mode',
                            3183: 'Fetal Heart Rate- Decelerations',
                            3184: 'Fetal Heart Rate- Accelerations',
                            3185: 'Peak inspiratory pressure',
                            3186: 'Plateau Inspiratory Pressure',
                            3187: 'Mean Inspiratory Pressure',
                            3188: 'Duration of Contractions',
                            3189: 'VTE Prophylaxis',
                            3190: 'Tidal Volume actual',
                            3191: 'Pain Location',
                            3192: 'Tidal Volume Set',
                            3193: 'National Early Warning Score (NEWS)',
                            3194: 'Cognition Assessment',
                            3195: 'Ventilator Respiratory Rate Actual',
                            3196: 'Clock-Drawing Test - Score',
                            3197: 'Clock-Drawing Test - Numbers',
                            3198: 'Ventilator Respiratory Rate Set',
                            3199: 'Ventilator I:E Ratio',
                            3200: 'Ventilator FiO2 % Measured',
                            3201: 'Clock-Drawing Test - Hands',
                            3202: 'Ventilator FiO2 % Set',
                            3203: 'Clock-Drawing Test - Hour Markers',
                            3204: 'Clock-Drawing Test - Face',
                            3205: 'Minute ventilation',
                            3206: 'Clock-Drawing Test - Comments',
                            3207: 'Clock-Drawing Test - Time',
                            3208: 'Clock-Drawing Test - Numbers Clockwise',
                            3209: 'Clock-Drawing Test - Indicates Target Time',
                            3210: 'Positive End Expiratory Pressure - Measured',
                            3211: 'Clock-Drawing Test - Clock Divided by 12',
                            3212: 'Positive End Expiratory Pressure - Set',
                            3213: 'Ventilator Pulmonary Compliance',
                            3214: 'Fresh Gas Flow Total (L/min)',
                            3215: 'Flows Oxygen (L/Min)',
                            3216: 'Clock-Drawing Test - Contour',
                            3217: 'Clock-Drawing Test - Details',
                            3218: 'Mini-Mental State Exam - Score',
                            3219: 'Mini-Mental State Exam - Details',
                            3220: 'Flows Air (L/min)',
                            3221: 'Mini Cog Assessment Score',
                            3222: 'Montreal Cognitive Assessment (MoCA) - Details',
                            3223: 'Montreal Cognitive Assessment (MoCA) - Score (out of 30)',
                            3224: 'Cognitive Screening: MoCA Total Score',
                            3225: 'Flows Nitrous Oxide (L/min)',
                            3226: 'MoCA:Delayed Recall (how many words did patient recall)',
                            3227: 'MoCA: Read the list of 5 words for the patient to remember',
                            3228: 'MoCA: Oriented to Year?',
                            3229: 'MoCA: Oriented to Place?',
                            3230: 'Respiratory Rate Actual from EtCO2 tracing',
                            3231: 'MoCA: Oriented to Month?',
                            3232: 'MoCA: Oriented to Day?',
                            3233: 'Inspired CO2 %',
                            3234: 'Inspired CO2 (mmHg)',
                            3235: 'End Tidal CO2 (mmHg)',
                            3236: 'End Tidal CO2 %',
                            3237: 'MoCA: Oriented to Date?',
                            3238: 'Inspired Nitrogen %',
                            3239: 'Expired Nitrogen %',
                            3240: 'Oxygen Insp %',
                            3241: 'MoCA: Oriented to City?',
                            3242: 'MoCA: Fluency: Name as many words that start with the letter "F" that you can (1 min)',
                            3243: 'Confusion Assessment Method (CAM) Altered LOC',
                            3244: 'Confusion Assessment Method (CAM) Disorganized Thinking',
                            3245: 'Oxygen Exp %',
                            3246: 'Confusion Assessment Method (CAM) Inattention',
                            3247: 'Confusion Assessment Method (CAM) Acute Mental Change and Fluctuating Course',
                            3248: 'Confusion Assessment Method (CAM) - Overall CAM-ICU Score',
                            3249: 'Confusion Assessment Method (CAM) Overall CAM-ICU/Short CAM Score',
                            3250: 'Nitrous Insp %',
                            3251: 'Confusion Assessment Method (CAM) - Overall CAM-ICU Modified Score',
                            3252: 'CAPD - Cornell Assessment of Pediatric Delirium Result',
                            3253: 'CAPD - Does the child make eye contact with the caregiver?',
                            3254: "CAPD - Are the child's actions purposeful?",
                            3255: 'Nitrous Exp %',
                            3256: 'CAPD - Is the child aware of his/her surroundings?',
                            3257: 'CAPD - Does the child communicate needs and wants?',
                            3258: 'CAPD - Is the child restless?',
                            3259: 'CAPD - Is the child inconsolable?',
                            3260: 'Isoflurane Exp %',
                            3261: 'CAPD - Is the child underactive-very little movement while awake?',
                            3262: 'CAPD - Does it take the child a long time to respond to interactions?',
                            3263: 'Temperature - Arterial Bypass Cannula',
                            3264: 'Temperature - Venous Bypass Cannula',
                            3265: 'Isoflurane Insp %',
                            3266: 'Noninvasive blood pressure cuff location',
                            3267: 'AD8 – Problems with Judgment',
                            3268: 'AD8 – Less interest in hobbies/activities',
                            3269: 'AD8 – Repeats the same things',
                            3270: 'Sevoflurane Exp %',
                            3271: 'AD8 – Trouble Learning',
                            3272: 'AD8 – Forgets correct month or year',
                            3273: 'AD8 – Trouble handling complicated financial affairs',
                            3274: 'AD8 – Trouble remembering appointments',
                            3275: 'Sevoflurane Insp %',
                            3276: 'AD8 – Daily problems with thinking and/or memory',
                            3277: 'AD8 – Total score',
                            3278: '4AT- AMT4',
                            3279: '4AT – Alertness',
                            3280: 'Desflurane Exp %',
                            3281: '4AT – Attention',
                            3282: '4AT – Acute Change or Fluctuating Course',
                            3283: '4AT – Total Score',
                            3284: 'Hopkins Frailty – Weight Loss',
                            3285: 'Desflurane Insp %',
                            3286: 'Hopkins Frailty – Exhaustion',
                            3287: 'Hopkins Frailty – Weak',
                            3288: 'Hopkins Frailty- Slow',
                            3289: 'Hopkins Frailty – Low activity',
                            3290: 'Halothane Exp %',
                            3291: 'Hopkins Frailty- Score',
                            3292: 'Fall Risk- Score',
                            3293: 'Rhythm/Pattern (Respiratory)',
                            3294: 'Temperature - Cardioplegia',
                            3295: 'Halothane Insp %',
                            3296: 'Nitrous Oxide Total Consumption (L)',
                            3297: 'Enflurane Exp %',
                            3298: 'Enflurane Insp %',
                            3299: 'Miscellaneous Volatile Agent Insp %',
                            3300: 'Miscellaneous Volatile Agent Exp %',
                            3301: 'Nitric Oxide Inhaled (ppm)',
                            3302: 'Air Total Consumption (L)',
                            3303: 'Oxygen Total Consumption (L)',
                            3304: 'rSO2 Index - Left Somatic',
                            3305: 'rSO2 Index - Right Somatic',
                            3306: 'rSO2 Index - Left Cerebral',
                            3307: 'rSO2 Index - Right Cerebral',
                            3308: 'CHEWS Score: Behavior/Neuro',
                            3309: 'CHEWS Score: Cardiovascular',
                            3310: 'BIS - Overall Trend (BIS Value)',
                            3311: 'BIS - Quality Index',
                            3312: 'Processed EEG Trend (unspecified device, PSI or BIS or Entropy)',
                            3313: 'BIS - EMG',
                            3314: 'Processed EEG Trend - spectral edge frequency',
                            3315: 'Entropy (State Entropy)',
                            3316: 'Entropy (Response Entropy)',
                            3317: 'CHEWS Score: Respiratory',
                            3318: 'CHEWS Score: Staff Concern',
                            3319: 'Fetal Heart Rate (C)',
                            3320: 'Fetal Heart Rate (A)',
                            3321: 'Fetal Heart Rate (B)',
                            3322: 'Tocodynamometry',
                            3323: 'Intrauterine Pressure',
                            3324: 'CHEWS Score: Family Concern',
                            3325: 'CHEWS Score: Color',
                            3326: "Children's Hospital Early Warning Score (CHEWS)",
                            3327: 'Expired Gas Control Mode (GE Aysis)',
                            3328: 'Anesthesia Machine Software Version',
                            3329: 'NINJA Score',
                            3330: 'Train-of-four Qualitative (Subjective, Clinician Reported) Count',
                            3331: 'Delirium Assessment Score (Watcha)',
                            3332: 'Processed EEG Monitor – Unspecified Device EMG Trend',
                            3333: 'Processed EEG Monitor - Unspecified Device Suppression Ratio',
                            3334: 'Entropy (BSR - Burst Suppression Ratio)',
                            3336: 'Perfusion – Cardiopulmonary bypass Arterial Temp',
                            3337: 'Perfusion – Cardiopulmonary bypass Continuous Arterial pH',
                            3338: 'Perfusion – Cardiopulmonary bypass Continuous Arterial PaCO2',
                            3339: 'Perfusion – Cardiopulmonary bypass Continuous Arterial PaO2',
                            3340: 'Cardiac Rhythm',
                            3341: 'Perfusion – Cardiopulmonary bypass Continuous Arterial HCO3',
                            3342: 'Perfusion – Cardiopulmonary bypass Continuous SvO2',
                            3343: 'Perfusion – Cardiopulmonary bypass Continuous HCT',
                            3344: 'Perfusion – Cardiopulmonary bypass Continuous Hgb',
                            3345: 'Face / Eyes checked',
                            3350: 'Systolic Pressure Variation',
                            3355: 'PVI %',
                            3470: 'Barometric Pressure',
                            3475: 'BP Sys Invasive Unspecified Site 5',
                            3476: 'BP Dias Invasive Unspecified Site 5',
                            3477: 'BP Mean Invasive Unspecified Site 5',
                            3480: 'Patient State Index - Overall Trend',
                            3481: 'Patient State Index - Suppression Ratio Trend',
                            3482: 'Patient State Index - EMG Trend',
                            3485: 'Train-of-four Quantitative (Objective) Ratio',
                            3486: 'Train-of-four Quantitative (Objective) Count and Ratio combined',
                            3487: 'Subjective Clinical Neuromuscular Monitoring Assessment (head lift, hand grasp)',
                            3488: 'Train-of-four Post Tetanic Count (PTC)',
                            3490: 'Miscellaneous Perfusionist Parameter',
                            3491: 'LVAD Flow (L/min)',
                            3492: 'Miscellaneous Primary Volatile Agent Name',
                            3493: 'Miscellaneous Secondary Volatile Agent Name',
                            3503: 'Sevoflurane (mmHg)',
                            3513: 'Ventilator Respiratory Rate Limit',
                            3533: 'Temperature Route',
                            3543: 'Ventilator - Pressure Support',
                            3553: 'Ventilator - Pressure Control',
                            3563: 'Ventilator - Inspiratory Time',
                            3573: 'Invasive arterial line pulse rate',
                            3580: 'Respiratory Rate - Unspecified source',
                            3590: 'Cardiac output - Unspecified source or technique',
                            3600: 'Cardiac index - Unspecified source or technique',
                            3701: 'BP Combined Invasive Unspecified Site 1',
                            3702: 'BP Combined Non-invasive',
                            3703: 'BP Combined Invasive Unspecified Site 4',
                            3704: 'BP Combined Arterial Line (Invasive, Peripheral)',
                            3705: 'BP Combined Invasive Unspecified Site 2',
                            3706: 'BP Combined Invasive Unspecified Site 3',
                            3707: 'BP Combined Aorta',
                            3708: 'BP Combined Invasive Unspecified Site 5',
                            50215: 'Delirium Assessment Score (PAED)',
                            50227: 'GI - Symptoms',
}

outcome_concept_ids = {
90000: 'unmapped outcome concept',
90001: 'intraoperative observed quality assurance event',
90002: 'postoperative visit patient pain score',
90003: 'postoperative visit patient satisfaction score',
90004: 'postoperative visit date / time',
90005: 'postoperative visit observed clinical events',
90006: 'pacu observed clinical event',
90007: 'phase i length of stay',
90008: 'postoperative hypothermia',
90009: 'ponv interventions',
90010: 'ponv assessment',
90011: 'categorized note - other postop complications',
90012: 'readmission assessment (lace)',
90013: 'postoperative anesthesia evaluation complete',
90100: 'actual procedure performed',
90101: 'post-procedure diagnosis',
90200: 'cpom measure death',
90201: 'cpom measure cardiac arrest',
90202: 'cpom measure myocardial ischemia',
90203: 'cpom measure anaphylaxis',
90204: 'cpom measure malignant hyperthermia',
90206: 'cpom measure stroke, cerebro-vascular accident, or coma',
90207: 'cpom measure visual loss',
90208: 'cpom measure operation on incorrect site',
90209: 'cpom measure operaton on incorrect patient',
90210: 'cpom measure incorrect procedure',
90211: 'cpom measure medication error',
90212: 'cpom measure unplanned icu admission',
90213: 'cpom measure intraoperative awareness',
90214: 'cpom measure unrecognized difficult airway',
90215: 'cpom measure reintubation',
90216: 'cpom measure dental trauma',
90217: 'cpom measure perioperative aspiration',
90218: 'cpom measure vascular access complication',
90219: 'cpom measure pneumothorax after vascular access or regional anesthesia',
90220: 'cpom measure infection following epidural or spinal anesthesia',
90221: 'cpom measure epidural hematoma following spinal or epidural anesthesia',
90222: 'cpom measure high spinal',
90223: 'cpom measure postdural puncture headache',
90224: 'cpom measure systemic local anesthetic toxicity',
90225: 'cpom measure neurologic deficit following regional anesthesia',
90226: 'cpom measure infection following peripheral nerve block',
90300: 'intraoperative - airway injury',
90301: 'intraoperative - airway obstruction',
90302: 'intraoperative - anaphylaxis',
90303: 'intraoperative - aspiration',
90304: 'intraoperative - bronchospasm',
90305: 'intraoperative - burn',
90306: 'intraoperative - cardiac arrest',
90307: 'intraoperative - new central nervous system deficit',
90308: 'coagulopathy',
90309: 'could not intubate',
90310: 'difficult intubation',
90311: 'death',
90312: 'cardiac arrest',
90313: 'dental injury',
90314: 'adverse drug reaction',
90315: 'dysrhythmia',
90316: 'emergency surgical airway',
90317: 'esophageal intubation',
90318: 'failed / inadequate block',
90319: 'failed / inadequate neuraxial technique',
90320: 'high spinal',
90321: 'infiltrated intravenous access',
90322: 'intraoperative awareness',
90323: 'laryngospasm',
90324: 'laryngeal mask airway inadequacy',
90325: 'malignant hyperthermia',
90326: 'ocular injury',
90327: 'peripheral nerve injury',
90328: 'pneumothorax',
90329: 'prolonged neuromuscular relaxation',
90330: 'reintubation',
90331: 'respiratory arrest during regional or sedation',
90332: 'seizure',
90333: 'skin / limb / joint injury',
90334: 'transfusion reaction',
90335: 'unplanned extubation',
90336: 'categorized event - cardiovascular',
90337: 'categorized event - neurologic (cns or pns)',
90338: 'categorized event - regional',
90339: 'categorized event - renal / urinary',
90340: 'categorized event - obstetric',
90341: 'categorized event - medication',
90342: 'postoperative visit vital signs - bp sys',
90343: 'postoperative visit vital signs - bp dias',
90344: 'postoperative visit vital signs - heart rate',
90345: 'postoperative visit vital signs - respiratory rate',
90346: 'postoperative visit vital signs - spo2 %',
90347: 'postoperative visit vital signs - temperature (c)',
90348: 'postoperative visit vital signs - temperature (f)',
90349: 'postoperative visit vital signs - temperature (unspecified scale)',
90350: 'postoperative visit physical exam level of consciousness',
90351: 'postoperative visit vital signs - oxygen supplementation / resp assist',
90352: 'event treated with',
90353: 'event root cause',
90354: 'categorized event - airway',
90355: 'event comment',
90356: 'postoperative visit comment',
90357: 'categorized event - equipment',
90358: 'categorized event - respiratory',
90359: 'categorized event - other, not listed',
90360: 'unplanned admission',
90361: 'case cancellation',
90371: 'postoperative nausea and/or vomiting',
90381: 'postoperative visit vital signs - bp sys/dias combined',
}

unit_conversions = {    # [multiplier, weight-dependent]
                        # standard bolus units: mg, ml, unit, puff
                        # standard time: min
                        'mcg': [1e-3, False],
                        'mg': [1, False],
                        'g': [1e3, False],
                        'l': [1e3, False],
                        'ml': [1, False],
                        'puff': [1, False],
                        'spray': [1, False],
                        'patch': [1, False],
                        'each': [1, False],
                        'meq': [1, False],
                        'units': [1, False],
                        '%': [1, False],
                        'ppm': [1, False],

                        'mcg/kg/hr': [1e-3/60, True],
                        'mg/kg/hr': [1/60, True],
                        'g/kg/hr': [1e3/60, True],
                        
                        'mcg/kg/min': [1e-3, True],
                        'mg/kg/min': [1, True],
                        'g/kg/min': [1e3, True],

                        'mcg/min': [1e-3, False],
                        'mcg/hr': [1e-3/60, False],
                        'mg/min': [1, False],
                        'mg/hr': [1/60, False],
                        'g/min': [1e3, False],
                        'g/hr': [1e3/60, False],
                        'units/hr': [1/60, False],
                        'units/min': [1, False],

                        'ml/hr': [1/60, False],
                        'ml/min': [1, False],
                    }
