import numpy as np

context = 5
max_horizon = 15
peri_intubation_period = [20, 5]

meds = [
        'meds_dexmedetomidine',
        'meds_ephedrine',
        'meds_esmolol',
        'meds_etomidate',
        'meds_epinephrine',
        'meds_fentanyl',
        'meds_glycopyrrolate',
        'meds_hydromorphone',
        'meds_ketamine',
        'meds_labetalol',
        'meds_norepinephrine',
        'meds_phenylephrine',
        'meds_propofol',
        'meds_remifentanil',
        'meds_vasopressin',
        ]
bolus_mins = {
        'meds_propofol': 20,
        'meds_phenylephrine': 0.050,
        'meds_norepinephrine': 0.008,
        'meds_epinephrine': 0.008,
        'meds_vasopressin': 0.5,
        'meds_ketamine': 5,
        'meds_remifentanil': 0.025,
        'meds_fentanyl': 0.0125,
        'meds_dexmedetomidine': 0.004,
        'meds_ephedrine': 1,
        'meds_esmolol': 5,
        'meds_glycopyrrolate': 0.05,
        'meds_labetalol': 2.5,
        'meds_hydromorphone': 0.1,
        'meds_etomidate': 4,
        }
bolus_maxs = {
        'meds_propofol': 400,
        'meds_phenylephrine': 0.600,
        'meds_norepinephrine': 0.032,
        'meds_epinephrine': 1.0,
        'meds_vasopressin': 5.0,
        'meds_ketamine': 100,
        'meds_remifentanil': 0.500,
        'meds_fentanyl': 1.0,
        'meds_dexmedetomidine': 0.120,
        'meds_ephedrine': 50,
        'meds_esmolol': 250,
        'meds_glycopyrrolate': 0.800,
        'meds_labetalol': 50,
        'meds_hydromorphone': 3.0,
        'meds_etomidate': 60,
        }
infusion_mins = { 
        'meds_propofol': 10,
        'meds_phenylephrine': 0.06,
        'meds_norepinephrine': 0.01,
        'meds_epinephrine': 0.01,
        'meds_vasopressin': 0.02,
        'meds_ketamine': 5,
        'meds_remifentanil': 0.03,
        'meds_dexmedetomidine': 0.4/60,
         'meds_ephedrine': 5,
        'meds_esmolol': 50,
        'meds_etomidate': 1,
        'meds_fentanyl': 0.1,
        'meds_glycopyrrolate': 0.1,
        'meds_hydromorphone': 0.05,
        'meds_labetalol': 1,
        }
infusion_rounding = {
        'meds_propofol': 5,
        'meds_phenylephrine': 0.1,
        'meds_remifentanil': 0.01,
        'meds_vasopressin': 0.02,
        'meds_epinephrine': 0.004,
        'meds_norepinephrine': 0.004,
        'meds_ketamine': 5,
        }
bolus_rounding = {
        'meds_propofol': 10,
        'meds_phenylephrine': 0.050,
        'meds_norepinephrine': 0.008,
        'meds_epinephrine': 0.008,
        'meds_vasopressin': 0.5,
        'meds_ketamine': 5,
        'meds_remifentanil': 0.025,
        'meds_fentanyl': 0.025,
        'meds_dexmedetomidine': 0.004,
        'meds_ephedrine': 5,
        'meds_esmolol': 10,
        'meds_glycopyrrolate': 0.05,
        'meds_labetalol': 2.5,
        'meds_hydromorphone': 0.1,
        'meds_etomidate': 2,
        }
bolus_typicals = {
        'meds_phenylephrine': [0.050, 0.100, 0.200],
        'meds_norepinephrine': [0.008, 0.004,],
        'meds_epinephrine': [0.008, 0.004,],
        'meds_vasopressin': [0.5, 1.0],
        'meds_fentanyl': [0.025, 0.050, 0.100, 0.150, 0.200, 0.250],
        'meds_dexmedetomidine': [0.004],
        'meds_ephedrine': [5, 10],
        'meds_glycopyrrolate': [0.2, 0.4],
        }
meds_use = ['meds_ephedrine',
            'meds_esmolol',
            'meds_fentanyl',
            'meds_glycopyrrolate',
            'meds_hydromorphone',
            'meds_ketamine',
            'meds_labetalol',
            'meds_phenylephrine',
            'meds_propofol',
        ]
meds_micrograms = [
        'meds_hydromorphone',
        'meds_fentanyl',
        'meds_glycopyrrolate',
        'meds_phenylephrine',
        'meds_dexmedetomidine',
        'meds_epinephrine',
        'meds_norepinephrine',
        'meds_remifentanil',
                   ]
meds_mcg = meds_micrograms
gases = [
        'phys_sevoflurane_exp_%',
        'phys_isoflurane_exp_%',
        'phys_desflurane_exp_%',
        'phys_nitrous_exp_%',
        ]
gas_mins = {
        'phys_sevoflurane_exp_%':0.05,
        'phys_desflurane_exp_%':1,
        'phys_isoflurane_exp_%':0.01,
        'phys_nitrous_exp_%':10,
        }
paralytics = [
            'meds_rocuronium',
            'meds_succinylcholine',
        ]
phys = [
            'phys_bp_sys_non_invasive',
            'phys_bp_dias_non_invasive',
            'phys_bp_mean_non_invasive',
            'phys_spo2_pulse_rate',
            'phys_spo2_%',
            'phys_end_tidal_co2_(mmhg)',
        ]
events = ['time_to_airway']
demog = ['age', 'sex', 'weight',]
demog_extended = demog + ['height']
input_features = meds + gases + phys + events + demog
output_features = phys
nicknames = {
                    'phys_bp_sys_non_invasive':'SBP',
                    'phys_bp_dias_non_invasive':'DBP',
                    'phys_bp_mean_non_invasive':'MAP',
                    'phys_spo2_pulse_rate':'HR',
                    'phys_spo2_%':'SpO2',
                    'phys_end_tidal_co2_(mmhg)':'etCO2',
                    'phys_sevoflurane_exp_%':'sevo',
                    'phys_desflurane_exp_%':'des',
                    'phys_isoflurane_exp_%':'iso',
                    'phys_nitrous_exp_%':'n2o',
                    'meds_dexmedetomidine':'dex',
                    'meds_ephedrine':'ephed',
                    'meds_epinephrine':'epi',
                    'meds_esmolol':'esmo',
                    'meds_etomidate':'etom',
                    'meds_fentanyl':'fent',
                    'meds_glycopyrrolate':'glyco',
                    'meds_hydromorphone':'dil',
                    'meds_ketamine':'ket',
                    'meds_labetalol':'labet',
                    'meds_norepinephrine':'norepi',
                    'meds_phenylephrine':'neo',
                    'meds_propofol':'prop',
                    'meds_remifentanil':'remi',
                    'meds_vasopressin':'vaso',
            }
full_nicknames = {
                    'phys_bp_sys_non_invasive':'SBP',
                    'phys_bp_dias_non_invasive':'DBP',
                    'phys_bp_mean_non_invasive':'MAP',
                    'phys_spo2_pulse_rate':'HR',
                    'phys_spo2_%':'SpO2',
                    'phys_end_tidal_co2_(mmhg)':'etCO2',
                    'phys_sevoflurane_exp_%':'sevoflurane',
                    'phys_desflurane_exp_%':'desflurane',
                    'phys_isoflurane_exp_%':'isoflurane',
                    'phys_nitrous_exp_%':'n2o',
                    'meds_dexmedetomidine':'dexmedetomidine',
                    'meds_ephedrine':'ephedrine',
                    'meds_epinephrine':'epinephrine',
                    'meds_esmolol':'esmolol',
                    'meds_etomidate':'etomidate',
                    'meds_fentanyl':'fentanyl',
                    'meds_glycopyrrolate':'glycopyrrolate',
                    'meds_hydromorphone':'hydromorphone',
                    'meds_ketamine':'ketamine',
                    'meds_labetalol':'labetalol',
                    'meds_norepinephrine':'norepinephrine',
                    'meds_phenylephrine':'phenylephrine',
                    'meds_propofol':'propofol',
                    'meds_remifentanil':'remifentanil',
                    'meds_vasopressin':'vasopressin',
            }
canonical_weight = 70.0
canonical_doses = {
                    'meds_dexmedetomidine':0.004,
                    'meds_ephedrine':5,
                    'meds_epinephrine':0.004,
                    'meds_esmolol':20,
                    'meds_etomidate':8,
                    'meds_fentanyl':0.050,
                    'meds_glycopyrrolate':0.2,
                    'meds_hydromorphone':0.4,
                    'meds_ketamine':10,
                    'meds_labetalol':5,
                    'meds_norepinephrine':0.004,
                    'meds_phenylephrine':0.100,
                    'meds_propofol':50,
                    'meds_remifentanil':0.050,
                    'meds_vasopressin':1,
        }
clip_limits = {
            'meds_atropine': 1.0,
            'meds_calcium chloride': 2000.0,
            'meds_cefazolin': 2000.0,
            'meds_dexamethasone': 12.0,
            'meds_dexmedetomidine': 0.100,
            'meds_ephedrine': 20.0,
            'meds_epinephrine': 1.0,
            'meds_esmolol': 100.0,
            'meds_etomidate': 40.0,
            'meds_fentanyl': 0.500,
            'meds_glycopyrrolate': 0.4,
            'meds_hydralazine': 30.0,
            'meds_hydromorphone': 4.0,
            'meds_ketamine': 250.0,
            'meds_labetalol': 100.0,
            'meds_lidocaine': 300.0,
            'meds_metoprolol': 50.0,
            'meds_midazolam': 10.0,
            'meds_norepinephrine': 0.050,
            'meds_ondansetron': 8.0,
            'meds_phenylephrine': 0.500,
            'meds_propofol': 400.0,
            'meds_remifentanil': 0.500,
            'meds_rocuronium': 150.0,
            'meds_succinylcholine': 200.0,
            'meds_vasopressin': 2.0,
            'phys_bp_dias_arterial_line_(invasive,_peripheral)': [0, 150],
            'phys_bp_dias_non_invasive': [0, 150],
            'phys_bp_mean_arterial_line_(invasive,_peripheral)': [0, 200],
            'phys_bp_mean_non_invasive': [0, 200],
            'phys_bp_sys_arterial_line_(invasive,_peripheral)': [0, 250],
            'phys_bp_sys_non_invasive': [0, 250],
            'phys_end_tidal_co2_(mmhg)': [0, 80],
            'phys_exhaled_monitor_calculated_mac_equivalent': [0, 3.0],
            'phys_inhaled_monitor_calculated_mac_equivalent': [0, 3.0],
            'phys_isoflurane_exp_%': [0, 4.0],
            'phys_mean_inspiratory_pressure': [0, 20.0],
            'phys_nitrous_exp_%': [0, 80.0],
            'phys_nitrous_insp_%': [0, 80.0],
            'phys_peak_inspiratory_pressure': [0, 70.0],
            'phys_respiratory_rate_actual_from_etco2_tracing': [0, 60.0],
            'phys_sevoflurane_exp_%': [0, 8.0],
            'phys_spo2_%': [30.0, 100.0],
            'phys_spo2_pulse_rate': [25.0, 300.0],
            'phys_tidal_volume_actual': [0.0, 1500],
            'phys_ventilator_fio2_%_measured': [20.0, 100.0],
        }
min_steps = {
        'meds_ephedrine': 0.5,
        'meds_esmolol': 3,
        'meds_etomidate': 1,
        'meds_fentanyl': 0.025,
        'meds_glycopyrrolate': 0.050,
        'meds_hydromorphone': 0.050,
        'meds_ketamine': 1,
        'meds_labetalol': 3,
        'meds_phenylephrine': 0.050,
        'meds_propofol': 10,
        'phys_sevoflurane_exp_%': 0.5,
        'phys_desflurane_exp_%': 2.0,
        'phys_isoflurane_exp_%': 0.25,
        'phys_nitrous_exp_%': 25,
        'phys_bp_sys_arterial_line_(invasive,_peripheral)': 10,
        'phys_bp_dias_arterial_line_(invasive,_peripheral)': 10,
        'phys_bp_mean_arterial_line_(invasive,_peripheral)': 10,
        'phys_spo2_pulse_rate': 15,
        'phys_spo2_%': 3,
        'phys_end_tidal_co2_(mmhg)': 10,
        }
colors = {
                'meds_propofol': 'gold',
                'meds_etomidate': 'gold',
                'meds_ketamine':  'gold',
                'meds_dexmedetomidine': 'gold',
                'meds_ondansetron': 'goldenrod',
                'meds_midazolam': 'orange',
                'meds_fentanyl': 'lightblue',
                'meds_remifentanil': 'lightblue',
                'meds_sufentanil': 'lightblue',
                'meds_alfentanil': 'lightblue',
                'meds_hydromorphone': 'lightblue',
                'meds_morphine': 'lightblue',
                'meds_methadone': 'lightblue',
                'meds_glycopyrrolate': 'green',
                'meds_atropine': 'green',
                'meds_nitroglycerin': 'purple',
                'meds_labetalol': 'purple',
                'meds_hydralazine': 'purple',
                'meds_phenylephrine': 'purple',
                'meds_epinephrine': 'purple',
                'meds_norepinephrine': 'purple',
                'meds_ephedrine': 'purple',
                'meds_esmolol': 'purple',
                'meds_succinylcholine': 'red',
                'meds_rocuronium': 'red',
                'meds_sugammadex': 'pink',
                'meds_normosol': 'dimgrey',
                'meds_cefazolin': 'dimgrey',
                'meds_vasopressin': 'purple',
                
                'phys_spo2_pulse_rate': '#52d211',
                'phys_spo2_%': '#0000F5',
                'phys_bp_dias_non_invasive': 'violet',
                'phys_bp_sys_non_invasive': 'violet',
                'phys_bp_mean_non_invasive': 'red',
                'phys_bp_sys_arterial_line_(invasive,_peripheral)': '#E087E8',
                'phys_bp_dias_arterial_line_(invasive,_peripheral)': '#E087E8',
                'phys_bp_mean_arterial_line_(invasive,_peripheral)': '#EA3325',
                'phys_end_tidal_co2_(mmhg)': '#D0BA98',
                'phys_nitrous_exp_%': 'cornflowerblue',
                'phys_nitrous_insp_%': 'cornflowerblue',
                'phys_central_venous_pressure': 'blue',
                'phys_pulmonary_artery_pressure_mean': 'gold',
                'phys_pulmonary_artery_pressure_dias': 'gold',
                'phys_pulmonary_artery_pressure_sys': 'gold',
                'phys_temperature___bladder': 'tan',
                'phys_temperature___nasopharyngeal': 'tan',
                'phys_temperature___oropharyngeal': 'tan',
                'phys_temperature___esophageal': 'tan',
                'phys_isoflurane_exp_%': 'purple',
                'phys_sevoflurane_exp_%': 'gold',
                'phys_desflurane_exp_%': 'blue',
            }
color_darkening = {
        'lightblue': [84/255, 148/255, 171/255],
        'purple': [71/255,0/255,77/255],
        'gold': [166/255, 138/255, 17/255],
        }
phys_units = {
            'phys_bp_sys_non_invasive': 'mmHg',
            'phys_bp_dias_non_invasive': 'mmHg',
            'phys_bp_mean_non_invasive': 'mmHg',
            'phys_spo2_pulse_rate': 'bpm',
            'phys_spo2_%': '%',
            'phys_end_tidal_co2_(mmhg)': 'mmHg',
        }
# define features used in modeling (xgboost etc), and their names
keep_feat = np.ones(len(input_features) * context, dtype=bool)
for idx, inf in enumerate(input_features):
    if inf in demog:
        keep_feat[idx*context : idx*context + context - 1] = False # leaves one sample of this feature, zeroes out the rest of them
    else:
        continue
kfeat = [inf for inf in input_features if inf not in demog]
fnames = np.repeat(kfeat, context)
idxs = np.tile(np.arange(context), len(kfeat))
fnames = np.array([f'{full_nicknames.get(fn, fn)} @ t-{context-i}' for fn,i in zip(fnames, idxs)])
keep_feat_names = np.concatenate([fnames, demog])

